/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User
    media: Media
    'media-folders': MediaFolder
    navigation: Navigation
    pages: Page
    news: News
    'news-tags': NewsTag
  }
  globals: {
    'site-settings': SiteSettings
    footer: Footer
  }
}

/**
 * User
 */
export interface User {
  id: string
  name: string
  email: string
  role: 'admin' | 'user'
  avatar?: string | Media | null
  createdAt: string
  updatedAt: string
}

/**
 * Media
 */
export interface Media {
  id: string
  folder?: string | MediaFolder | null
  alt: string
  caption?: string | null
  uploadedBy?: string | User | null
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
    }
    tablet?: {
      url?: string | null
      width?: number | null
      height?: number | null
    }
  }
  createdAt: string
  updatedAt: string
}

/**
 * MediaFolder
 */
export interface MediaFolder {
  id: string
  name: string
  slug: string
  parent?: string | MediaFolder | null
  createdAt: string
  updatedAt: string
}

/**
 * Navigation
 */
export interface Navigation {
  id: string
  label: string
  linkType?: 'none' | 'page' | 'custom' | null
  page?: string | Page | null
  href?: string | null
  order: number
  openInNewTab?: boolean | null
  children?: NavigationChild[] | null
  createdAt: string
  updatedAt: string
}

export interface NavigationChild {
  label: string
  items?: NavigationChildItem[] | null
}

export interface NavigationChildItem {
  label: string
  linkType: 'page' | 'custom'
  page?: string | Page | null
  href?: string | null
  openInNewTab?: boolean | null
}

/**
 * Page
 */
export interface Page {
  id: string
  title: string
  pageType: 'home' | 'news' | 'leadership' | 'departments' | 'documents' | 'text'
  status: 'draft' | 'published' | 'archived'
  slug?: string | null
  content?: Record<string, unknown> | null
  blocks?: PageBlock[] | null
  seo?: SEOFields | null
  publishedDate?: string | null
  author?: string | User | null
  createdAt: string
  updatedAt: string
}

export type PageBlock =
  | SectionHeaderBlock
  | RichTextBlock
  | MarkdownTextBlock
  | ImageBlock
  | CallToActionBlock
  | NewsBlock
  | PersonPlaceBlock
  | TabBlock
  | MediaBlock
  | AccordionBlock

export interface SectionHeaderBlock {
  id?: string | null
  blockType: 'sectionHeader'
  type: 'small' | 'big'
  title: string
  subtitle?: string | null
  description?: string | null
  headingLevel?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | null
  badge?: {
    text?: string | null
    icon?: string | null
    gradient?: string | null
  } | null
  enableAnimation?: boolean | null
}

export interface RichTextBlock {
  id?: string | null
  blockType: 'richText'
  content: Record<string, unknown> | null
}

export interface MarkdownTextBlock {
  id?: string | null
  blockType: 'markdownText'
  markdown: string
  accentColor?: 'amber' | 'indigo' | 'purple' | 'green' | 'blue' | null
}

export interface ImageBlock {
  id?: string | null
  blockType: 'imageBlock'
  image: string | Media
  caption?: string | null
}

export interface CallToActionBlock {
  id?: string | null
  blockType: 'callToAction'
  heading: string
  description?: string | null
  link?: {
    label: string
    url: string
    openInNewTab?: boolean | null
  } | null
}

export interface NewsBlock {
  id?: string | null
  blockType: 'newsBlock'
  displayMode: 'list' | 'carousel' | 'grid'
  contentSource: 'all' | 'byTag' | 'manual'
  selectedTag?: string | NewsTag | null
  selectedNews?: (string | News)[] | null
  limit?: number | null
  enableSearch?: boolean | null
  enableFilters?: boolean | null
  enablePagination?: boolean | null
  itemsPerPage?: number | null
}

export interface PersonPlaceBlock {
  id?: string | null
  blockType: 'personPlaceBlock'
  displayMode: 'grid' | 'fullRow'
  itemsPerRow?: '3' | '4' | null
  items: {
    id?: string | null
    photo: string | Media
    name: string
    subtitle?: string | null
    description?: string | null
    customFields?: {
      id?: string | null
      label: string
      value: string
    }[] | null
    readMoreLink?: {
      enabled?: boolean | null
      url?: string | null
      openInNewTab?: boolean | null
    } | null
  }[]
}

export interface TabBlock {
  id?: string | null
  blockType: 'tabBlock'
  tabs: {
    id?: string | null
    tabName: string
    contentType: 'richText' | 'news' | 'images' | 'records'
    richTextContent?: Record<string, unknown> | null
    newsSource?: 'latest' | 'byTag' | 'manual' | null
    newsTag?: string | NewsTag | null
    selectedNews?: (string | News)[] | null
    newsLimit?: number | null
    images?: {
      id?: string | null
      image: string | Media
      caption?: string | null
    }[] | null
    records?: {
      id?: string | null
      recordType: 'richText' | 'image' | 'video' | 'imageCard'
      recordRichText?: Record<string, unknown> | null
      recordImage?: string | Media | null
      videoUrl?: string | null
      cardImage?: string | Media | null
      cardTitle?: string | null
      cardDescription?: string | null
      cardLink?: string | null
    }[] | null
  }[]
}

export interface MediaBlock {
  id?: string | null
  blockType: 'mediaBlock'
  title?: string | null
  displayMode: 'grid' | 'masonry' | 'carousel'
  columns?: '2' | '3' | '4' | null
  media: {
    id?: string | null
    image: string | Media
    caption?: string | null
  }[]
  enableLightbox?: boolean | null
}

export interface AccordionBlock {
  id?: string | null
  blockType: 'accordionBlock'
  title?: string | null
  description?: string | null
  allowMultiple?: boolean | null
  accordionItems: {
    id?: string | null
    itemTitle: string
    contentItems: {
      id?: string | null
      contentType: 'text' | 'richText' | 'image' | 'linkList'
      text?: string | null
      richText?: Record<string, unknown> | null
      image?: string | Media | null
      imageCaption?: string | null
      links?: {
        id?: string | null
        linkText: string
        linkUrl: string
        openInNewTab?: boolean | null
      }[] | null
    }[]
  }[]
}

/**
 * SEO Fields
 */
export interface SEOFields {
  metaTitle?: string | null
  focusKeyword?: string | null
  metaDescription?: string | null
  keywords?: string | null
  canonicalUrl?: string | null
  noIndex?: boolean | null
  noFollow?: boolean | null
  ogTitle?: string | null
  ogDescription?: string | null
  ogImage?: string | Media | null
  ogType?: 'website' | 'article' | 'blog' | null
  twitterCard?: 'summary_large_image' | 'summary' | null
  twitterTitle?: string | null
  twitterDescription?: string | null
  twitterImage?: string | Media | null
  metaImage?: string | Media | null
  // Allow additional fields for compatibility
  [key: string]: unknown
}

/**
 * News
 */
export interface News {
  id: string
  title: string
  slug: string
  status: 'draft' | 'published'
  publishedDate: string
  featuredImage?: string | Media | null
  tags?: (string | NewsTag)[] | null
  excerpt: string
  blocks?: NewsContentBlock[] | null
  seo?: SEOFields | null
  author: string | User
  authorNote?: string | null
  createdAt: string
  updatedAt: string
}

export type NewsContentBlock =
  | SectionHeaderBlock
  | RichTextBlock
  | MarkdownTextBlock
  | ImageBlock
  | CallToActionBlock

/**
 * NewsTag
 */
export interface NewsTag {
  id: string
  name: string
  slug: string
  color?: 'indigo' | 'blue' | 'purple' | 'green' | 'amber' | 'red' | 'pink' | 'teal' | null
  description?: string | null
  createdAt: string
  updatedAt: string
}

/**
 * SiteSettings Global
 */
export interface SiteSettings {
  id: string
  siteTitle: string
  siteLogo?: string | Media | null
  logoAltText?: string | null
  tagline?: string | null
  socialLinks?: SocialLink[] | null
  createdAt: string
  updatedAt: string
}

export interface SocialLink {
  platform:
    | 'facebook'
    | 'twitter'
    | 'instagram'
    | 'linkedin'
    | 'youtube'
    | 'tiktok'
    | 'github'
    | 'discord'
  url: string
  openInNewTab?: boolean | null
}

/**
 * Footer Global
 */
export interface Footer {
  id: string
  copyrightText?: string | null
  description?: string | null
  links?: FooterLink[] | null
  contactColumns?: ContactColumn[] | null
  createdAt: string
  updatedAt: string
}

export interface FooterLink {
  label: string
  href: string
  openInNewTab?: boolean | null
}

export interface ContactColumn {
  title: string
  items?: ContactItem[] | null
}

export interface ContactItem {
  icon: 'location' | 'phone' | 'email' | 'fax' | 'time' | 'link'
  label: string
  href?: string | null
  openInNewTab?: boolean | null
}
